add biopetTest command and test
biopet/sbt-biopet pull request #10
Opened 2018-01-18 13:26 UTC by rhpvorderman

This was not a priority, but stumbled across a very easy way to do this when researching another issue.

2018-01-31 12:08 UTC, ffinfo requested changes

2018-01-31 12:08 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetPlugin.scala
> +          "clean" ::
Clean should not be here

2018-01-31 14:57 UTC, rhpvorderman commented on src/main/scala/nl/biopet/sbtbiopet/BiopetPlugin.scala
> +          "clean" ::
@ffinfo Done

2018-02-01 08:45 UTC, ffinfo approved these changes

2018-02-01 09:24 UTC, merged