Integrate sbt-bioconda into biopet plugin
biopet/sbt-biopet pull request #21
Opened 2018-04-09 13:07 UTC by rhpvorderman

TODO:
- [ ] Release sbt-bioconda

2018-05-18 11:56 UTC, ffinfo requested changes

2018-05-18 11:56 UTC, ffinfo commented on Jenkinsfile
> +            sh "${tool name: 'sbt 0.13.15', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'}/bin/sbt -no-colors clean scalafmt test headerCheck"
Please update sbt here to 1.0.4

2018-05-24 09:23 UTC, ffinfo requested changes

2018-05-24 09:23 UTC, ffinfo commented on build.sbt
> +libraryDependencies += "org.testng" % "testng" % "6.14.2" % "test"
It's better practice to use `Test` instead of `"test"`

2018-05-24 09:23 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +package nl.biopet.sbtbiopet
Is this is not something to move to common-utils?

2018-05-24 09:23 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +      case None    => throw new Exception(s"Chapter not found: $chapter")
to generic Exception

2018-05-24 09:23 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +    val headingDepth = chapterRegex.findFirstMatchIn(markdown) match {
Just a suggestion, not required but maybe nicer:
```scala
chapterRegex.findFirstMatchIn(markdown)
  .map(_.group("hashtags").length)
  .getOrElse(throw new IllegalStateException(s"Chapter not found: $chapter"))
```

2018-05-24 09:23 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +      val regex = s"^(#{1,$headingDepth})[^#]([\\t ]*)(.*)$$".r
it's better to put the regex outside this method as a `private lazy val`. This way the regex is only created once.

2018-05-24 09:23 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +      val regex = s"^(#{1,$headingDepth})[^#]([\\t ]*)(.*)$$".r
this is true for all regexes

2018-05-24 09:23 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +    val correctChapter = chapters.find(lines => {
I think what you try to do here is this:
```scala
    chapters.find(lines => lines.headOption
      .exists(chapterRegex.findFirstMatchIn(_).isDefined))
      .map(lines => if (includeHeader) lines else lines.drop(1))
      .map(_.mkString(lineSeparator))
      .getOrElse(throw new IllegalStateException(
        "Cannot validate correct chapter after parsing. " +
          "Please contact application maintainers."))
```

2018-05-24 09:23 UTC, ffinfo commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +      case (result, line) =>
Double cases can sometimes be resolved into 1 like this:
```scala
    stringList.foldLeft(ListBuffer[ListBuffer[String]]()) {
      case (result, line) if splitter(line) || result.lastOption.isEmpty => 
        result += ListBuffer(line)
      case (result, line) =>
        result.last += line
        result
    }.map(buffer => buffer.toList).toList
```

Also if possible try to not use a val if it's not needed.

2018-05-24 10:04 UTC, rhpvorderman commented on src/main/scala/nl/biopet/sbtbiopet/BiopetUtils.scala
> +package nl.biopet.sbtbiopet
Yes. Let's do this for the next release.

2018-05-24 10:44 UTC, ffinfo approved these changes

2018-05-24 11:34 UTC, merged